name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Set up Ruby and install dependencies
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true

      # Install gem dependencies
      - name: Install dependencies
        run: bundle install

      # Build the site with Jekyll
      - name: Build site with Jekyll
        run: bundle exec jekyll build

      # Deploy the built site to GitHub Pages using Peaceiris action
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./_site
